local nldecl = require 'nldecl'

nldecl.include_names = {
  '^WGPU',
  '^wgpu',
}

nldecl.exclude_names = {
  -- Internal/private names
  _wgpu_COMMA = true,
  _wgpu_MAKE_INIT_STRUCT = true,
  _wgpu_SET_FN_ATTRS = true,
  _wgpu_FUNCTION_ATTRS = true,
  -- Proc pointer types (not needed for bindings, they're for function pointers)
  '^WGPUProc',
}

nldecl.include_macros = {
  uint32 = {
    WGPU_TRUE = true,
    WGPU_FALSE = true,
    WGPU_ARRAY_LAYER_COUNT_UNDEFINED = true,
    WGPU_COPY_STRIDE_UNDEFINED = true,
    WGPU_DEPTH_SLICE_UNDEFINED = true,
    WGPU_LIMIT_U32_UNDEFINED = true,
    WGPU_MIP_LEVEL_COUNT_UNDEFINED = true,
    WGPU_QUERY_SET_INDEX_UNDEFINED = true,
  },
  uint64 = {
    WGPU_LIMIT_U64_UNDEFINED = true,
    WGPU_WHOLE_SIZE = true,
  },
  csize = {
    WGPU_STRLEN = true,
    WGPU_WHOLE_MAP_SIZE = true,
  },
}

nldecl.prepend_code = [=[
--[[
  WebGPU bindings for Nelua
  Auto-generated by nelua-decl from webgpu.h and wgpu.h
  DO NOT EDIT MANUALLY - regenerate with: make generate

  Standard API: https://github.com/webgpu-native/webgpu-headers
  wgpu-native:  https://github.com/gfx-rs/wgpu-native
]]

##[[
cinclude '"webgpu/webgpu.h"'
cinclude '"webgpu/wgpu.h"'
linklib 'wgpu_native'
if ccinfo.is_linux then
  linklib 'dl'
  linklib 'pthread'
  linklib 'm'
end
]]
]=]

nldecl.append_code = [[
-- End of auto-generated WebGPU bindings
]]
