#!/usr/bin/env python3
"""
extract_macros.py - Extract C macro constants from WebGPU headers
and generate Nelua constant definitions.

nelua-decl cannot automatically handle C preprocessor macros,
so this script parses them and generates corresponding Nelua globals.

Usage:
    python3 extract_macros.py webgpu.h [wgpu.h] > webgpu_macros.nelua
"""

import re
import sys
import os
from datetime import datetime


def parse_simple_macros(header_path):
    """Parse #define macros that resolve to simple constant values."""
    macros = []
    with open(header_path, 'r') as f:
        content = f.read()

    # Match single-line #define WGPU_NAME (VALUE)
    # Handles: integers, hex, UINT32_MAX, UINT64_MAX, SIZE_MAX, NAN, etc.
    pattern = re.compile(
        r'#define\s+(WGPU_[A-Z_0-9]+)\s+\(?(UINT32_C\(\d+\)|UINT64_C\(\d+\)|'
        r'UINT32_MAX|UINT64_MAX|SIZE_MAX|NAN|'
        r'0x[0-9A-Fa-f]+|[0-9]+)\)?'
    )

    for match in pattern.finditer(content):
        name = match.group(1)
        value = match.group(2)

        # Skip internal/attribute macros
        if name in ('WGPU_OBJECT_ATTRIBUTE', 'WGPU_ENUM_ATTRIBUTE',
                     'WGPU_STRUCTURE_ATTRIBUTE', 'WGPU_FUNCTION_ATTRIBUTE',
                     'WGPU_NULLABLE', 'WGPU_EXPORT', 'WGPU_SHARED_LIBRARY',
                     'WGPU_BUILDING_SHARED_LIBRARY'):
            continue

        # Determine Nelua type and value
        nelua_type, nelua_value = convert_macro_value(name, value)
        if nelua_type:
            macros.append((name, nelua_type, nelua_value, value))

    return macros


def convert_macro_value(name, c_value):
    """Convert a C macro value to Nelua type and value."""
    # Boolean constants
    if c_value in ('UINT32_C(1)',):
        return 'uint32', '1'
    if c_value in ('UINT32_C(0)',):
        return 'uint32', '0'

    # UINT32_C(n)
    m = re.match(r'UINT32_C\((\d+)\)', c_value)
    if m:
        return 'uint32', m.group(1)

    # UINT64_C(n)
    m = re.match(r'UINT64_C\((\d+)\)', c_value)
    if m:
        return 'uint64', m.group(1)

    # Special max values
    if c_value == 'UINT32_MAX':
        return 'uint32', '0xFFFFFFFF'
    if c_value == 'UINT64_MAX':
        return 'uint64', '0xFFFFFFFFFFFFFFFF'
    if c_value == 'SIZE_MAX':
        return 'usize', '(@usize)(-1)'

    # NAN
    if c_value == 'NAN':
        return 'float32', '0.0/0.0'

    # Hex literals
    if c_value.startswith('0x'):
        val = int(c_value, 16)
        if val <= 0xFFFFFFFF:
            return 'uint32', c_value
        else:
            return 'uint64', c_value

    # Plain integers
    if c_value.isdigit():
        val = int(c_value)
        if val <= 0xFFFFFFFF:
            return 'uint32', c_value
        else:
            return 'uint64', c_value

    return None, None


def parse_init_macros(header_path):
    """Parse _INIT struct initializer macros (multi-line)."""
    init_macros = []
    with open(header_path, 'r') as f:
        content = f.read()

    # Find all *_INIT macros
    pattern = re.compile(r'#define\s+(WGPU_[A-Z_0-9]+_INIT)\s+')
    for match in pattern.finditer(content):
        name = match.group(1)
        # Extract the struct type name: WGPU_FOO_BAR_INIT -> WGPUFooBar
        init_macros.append(name)

    return init_macros


def generate_nelua(macros, init_macro_names, header_files):
    """Generate Nelua source code for the extracted macros."""
    lines = []

    lines.append('--[[')
    lines.append('  WebGPU macro constants for Nelua')
    lines.append(f'  Auto-generated by extract_macros.py on {datetime.now().strftime("%Y-%m-%d")}')
    lines.append(f'  Source headers: {", ".join(os.path.basename(h) for h in header_files)}')
    lines.append('')
    lines.append('  DO NOT EDIT MANUALLY - regenerate with: make macros')
    lines.append(']]')
    lines.append('')
    lines.append("require 'wgpu-c.webgpu'")
    lines.append('')

    # Group macros by category
    bool_macros = [(n, t, v, c) for n, t, v, c in macros if n in ('WGPU_TRUE', 'WGPU_FALSE')]
    limit_macros = [(n, t, v, c) for n, t, v, c in macros
                    if 'UNDEFINED' in n or 'WHOLE' in n or 'STRLEN' in n]
    other_macros = [(n, t, v, c) for n, t, v, c in macros
                    if (n, t, v, c) not in bool_macros and (n, t, v, c) not in limit_macros]

    if bool_macros:
        lines.append('-- Boolean constants')
        for name, nelua_type, nelua_value, c_value in bool_macros:
            lines.append(f'global {name}: {nelua_type} <comptime> = {nelua_value} -- {c_value}')
        lines.append('')

    if limit_macros:
        lines.append('-- Sentinel / undefined values')
        for name, nelua_type, nelua_value, c_value in limit_macros:
            lines.append(f'global {name}: {nelua_type} <comptime> = {nelua_value} -- {c_value}')
        lines.append('')

    if other_macros:
        lines.append('-- Other constants')
        for name, nelua_type, nelua_value, c_value in other_macros:
            lines.append(f'global {name}: {nelua_type} <comptime> = {nelua_value} -- {c_value}')
        lines.append('')

    if init_macro_names:
        lines.append('-- Note: _INIT struct macros are not directly translatable.')
        lines.append('-- Use Nelua\'s default zero-initialization or create helper functions.')
        lines.append('-- The following _INIT macros exist in the C headers:')
        for name in sorted(init_macro_names)[:10]:  # Show first 10 as examples
            lines.append(f'--   {name}')
        if len(init_macro_names) > 10:
            lines.append(f'--   ... and {len(init_macro_names) - 10} more')
        lines.append('')

    return '\n'.join(lines)


def main():
    if len(sys.argv) < 2:
        print(f'Usage: {sys.argv[0]} <header.h> [header2.h ...]', file=sys.stderr)
        sys.exit(1)

    header_files = sys.argv[1:]
    all_macros = []
    all_init_macros = []

    for header in header_files:
        if not os.path.exists(header):
            print(f'Warning: {header} not found, skipping', file=sys.stderr)
            continue
        all_macros.extend(parse_simple_macros(header))
        all_init_macros.extend(parse_init_macros(header))

    # Deduplicate
    seen = set()
    unique_macros = []
    for m in all_macros:
        if m[0] not in seen:
            seen.add(m[0])
            unique_macros.append(m)

    output = generate_nelua(unique_macros, all_init_macros, header_files)
    print(output)


if __name__ == '__main__':
    main()
