#!/bin/bash
# fetch_headers.sh - Download latest WebGPU headers from upstream
#
# This script fetches:
#   1. webgpu.h from webgpu-native/webgpu-headers (the standard)
#   2. wgpu.h from gfx-rs/wgpu-native (native extensions)
#
# Usage:
#   ./scripts/fetch_headers.sh [--tag <version>]
#
# Examples:
#   ./scripts/fetch_headers.sh              # latest from trunk
#   ./scripts/fetch_headers.sh --tag v27.0.4.0  # specific version

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CODEGEN_DIR="$PROJECT_DIR/wgpu-c/codegen"
VERSION_FILE="$PROJECT_DIR/VERSION"

# Default: latest from main/trunk branches
WEBGPU_H_BRANCH="main"
WGPU_NATIVE_BRANCH="trunk"

# Parse arguments
WGPU_TAG=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --tag)
            WGPU_TAG="$2"
            WGPU_NATIVE_BRANCH="$WGPU_TAG"
            shift 2
            ;;
        --help|-h)
            echo "Usage: $0 [--tag <version>]"
            echo ""
            echo "Options:"
            echo "  --tag <version>   Download headers for a specific wgpu-native release"
            echo "                    Example: --tag v27.0.4.0"
            echo ""
            echo "Without --tag, downloads the latest from main/trunk branches."
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

echo "=== Fetching WebGPU Headers ==="
echo ""

# 1. Download webgpu.h (standard API)
echo "Downloading webgpu.h (branch: $WEBGPU_H_BRANCH)..."
WEBGPU_H_URL="https://raw.githubusercontent.com/webgpu-native/webgpu-headers/$WEBGPU_H_BRANCH/webgpu.h"
curl -sL -o "$CODEGEN_DIR/webgpu.h" "$WEBGPU_H_URL"
WEBGPU_LINES=$(wc -l < "$CODEGEN_DIR/webgpu.h")
echo "  -> webgpu.h: $WEBGPU_LINES lines"

# 2. Download wgpu.h (native extensions)
echo "Downloading wgpu.h (branch: $WGPU_NATIVE_BRANCH)..."
WGPU_H_URL="https://raw.githubusercontent.com/gfx-rs/wgpu-native/$WGPU_NATIVE_BRANCH/ffi/wgpu.h"
curl -sL -o "$CODEGEN_DIR/wgpu.h" "$WGPU_H_URL"
WGPU_LINES=$(wc -l < "$CODEGEN_DIR/wgpu.h")
echo "  -> wgpu.h: $WGPU_LINES lines"

# 3. Get version information
echo ""
echo "Fetching latest wgpu-native release info..."
LATEST_TAG=$(curl -s "https://api.github.com/repos/gfx-rs/wgpu-native/releases/latest" \
    | python3 -c "import sys,json; print(json.load(sys.stdin).get('tag_name','unknown'))" 2>/dev/null \
    || echo "unknown")

# 4. Write version file
cat > "$VERSION_FILE" << EOF
# nelua-wgpu version tracking
# Auto-generated by fetch_headers.sh

WEBGPU_HEADERS_BRANCH=$WEBGPU_H_BRANCH
WGPU_NATIVE_BRANCH=$WGPU_NATIVE_BRANCH
WGPU_NATIVE_LATEST=$LATEST_TAG
FETCH_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Header stats
WEBGPU_H_LINES=$WEBGPU_LINES
WGPU_H_LINES=$WGPU_LINES
EOF

echo ""
echo "=== Summary ==="
echo "  webgpu.h:            $WEBGPU_LINES lines (branch: $WEBGPU_H_BRANCH)"
echo "  wgpu.h:              $WGPU_LINES lines (branch: $WGPU_NATIVE_BRANCH)"
echo "  Latest wgpu-native:  $LATEST_TAG"
if [ -n "$WGPU_TAG" ]; then
    echo "  Pinned to tag:       $WGPU_TAG"
fi
echo "  Version file:        $VERSION_FILE"
echo ""
echo "Next step: cd wgpu-c/codegen && make generate"
